### ISSUE TITLE
version 1.1.1

### ISSUE THREAD

**Issue by chicoff** [leehooi/vs-external-tools#2]
Hello thank you for introducing the clipboard option.
I tested version 1.1.1 on vscode  and vscode insiders and the external command is not executed. How can I debug? I'm on ubuntu 17.10

This is my configuration:
"vs-external-tools.externalCommand1.command": "meld",
"vs-external-tools.externalCommand1.args": ["$(ItemPath)","$(Clipboard)"],
"vs-external-tools.externalCommand1.cwd": "$(ItemDir)"

**Comment by chicoff** [comment]
solved! on ubuntu the package xsel is needed
sudo apt install xsel

**Comment by leehooi** [comment]
Cool
